In [ ]:
#1
import numpy as np

a=np. arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#2

import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#3
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4
import numpy as np
c=np.arange(0,1,0.1)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#5
import numpy as np
x=np.zeros(10)
print(x)
c=np.ones(10)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
##..ARRAY INDEXING..
#6

x=np.array([10,20,30,40,50])
print(x[2])

30


In [ ]:
#7

a=np.array([[1,2,3,4],[7,5,6,8],[6,7,4,6]])
print(a)
print(a[1,2])


[[1 2 3 4]
 [7 5 6 8]
 [6 7 4 6]]
6


In [ ]:
#8
a=np.array([5,10,15,20,25])
print(a[4])

25


In [ ]:
#9
a=np.array([1,3,5,7,9,11])
print(a[1])
print(a[3])
print(a[4])

3
7
9


In [ ]:
#10
import numpy as np
x=np.array([[[1,2],[3,4]],[[5,6],[8,9]]])

print(x)
print(x[1,1,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [8 9]]]
9


In [ ]:
##ARRAY SLICING
#11
a=np.array([2,4,6,8,10,12])
print()

[ 2  4  6  8 10 12]


In [10]:
##12

import numpy as np
a=np.array([[2,3,4,5],[6,7,8,9],[1,2,3,4],[4,3,7,1]])
print(a)
print("")
print(a[:2,2:])

[[2 3 4 5]
 [6 7 8 9]
 [1 2 3 4]
 [4 3 7 1]]

[[4 5]
 [8 9]]


In [2]:
##
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a[::2])

[0 2 4 6 8]


In [3]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[8,9,4,5]])
print(a)
print("")
print(a[0:,2:])

[[1 2 3 4]
 [5 6 7 8]
 [8 9 4 5]]

[[3 4]
 [7 8]
 [4 5]]


In [7]:
import numpy as np
a=np.array([[4,5,6,7,8],[6,7,8,9,7],[1,2,3,4,5],[7,5,4,3,2],[9,7,8,3,2]])
print(a)
print("")
print(a[1:4,1:4])

[[4 5 6 7 8]
 [6 7 8 9 7]
 [1 2 3 4 5]
 [7 5 4 3 2]
 [9 7 8 3 2]]

[[7 8 9]
 [2 3 4]
 [5 4 3]]


In [8]:
import numpy as np
a=np.array([0,1,2,3,4,5,])
print(a)
print('')
b=a.astype("f")


[0 1 2 3 4 5]

